spring:
  main:
    allow-bean-definition-overriding: 'true'
  application:
    name: autorizador-api
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

message-error:
  country: "BR"
  language: "pt-br"